version: "3.9"

services:
  app:
    container_name: node_api_pjcash
    build: .
    ports:
      - 3000:3000 # LOCAL:DOCKER
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - .:/app

  postgres:
    container_name: pj_cash
    image: postgres:latest
    ports:
      - 5433:5432 # LOCAL:DOCKER
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
